<a href="https://colab.research.google.com/github/meghanjukl-meg/ICTK_Assignment/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Problems


In [1]:
import numpy as np
import pandas as pd

1. BasicArrayOperations

Convert the mpg column into a NumPy array and calculate:

○ The mean, median, and standard deviation of mpg.

In [2]:
df = pd.read_csv('auto-mpg.csv')
#'mpg' column to a NumPy array
mpg_array = df['mpg'].to_numpy()
mpg_array

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [41]:
#mean
np.mean(mpg_array)

np.float64(23.514572864321607)

In [42]:
#median
np.median(mpg_array)

np.float64(23.0)

In [43]:
#stddeviation
np.std(mpg_array)

np.float64(7.806159061274433)

In [44]:
# The number of cars with mpg greater than 25.
number = np.sum(mpg_array >25 )
number

np.int64(158)

2. Filtering

Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list.

In [45]:
df.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   
5  15.0          8         429.0       198.0    4341          10.0   
6  14.0          8         454.0       220.0    4354           9.0   
7  14.0          8         440.0       215.0    4312           8.5   
8  14.0          8         455.0       225.0    4425          10.0   
9  15.0          8         390.0       190.0    3850           8.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   
5          70       1           ford galaxie 500               0.045612   
6          70       1           chevrolet impala               0.050528   
7          70       1          plymouth fury iii               0.049861   
8          70       1           pontiac catalina               0.050847   
9          70       1         amc ambassador dpl               0.049351   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754  
5           0.034554  
6           0.028939  
7           0.027597  
8           0.031638  
9           0.033117

In [3]:
data_cars = np.genfromtxt('auto-mpg.csv', delimiter=',', dtype=None, names=True)
#data_cars
car_cyl = data_cars['cylinders'] > 6
#car_cyl
car_names_list = data_cars['car_name'][car_cyl].tolist()
car_names_list

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

3. StatisticalAnalysis

Compute the 25th, 50th, and 75th percentiles of the weight column.

In [46]:
wgt_array = df['weight'].to_numpy()
#wgt_array
percentiles = np.percentile(wgt_array, [25, 50, 75])
print(f"25th Percentile:{percentiles[0]}")
print(f"50th Percentile: {percentiles[1]}")
print(f"75th Percentile: {percentiles[2]}")

25th Percentile:2223.75
50th Percentile: 2803.5
75th Percentile: 3608.0


4. ArrayManipulation

Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [5]:
acc_array = df['acceleration'].to_numpy()
#acc_array
acc_min = acc_array.min()
acc_max = acc_array.max()
norma_acc = (acc_array - acc_min) / (acc_max - acc_min)
norma_acc

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

5. Broadcasting

Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.

In [6]:
h_power_arr =df['horsepower'].to_numpy()
#h_power_arr
#conv to float
##hp_float = h_power_arr.astype(float)
hp_float = pd.to_numeric(h_power_arr, errors='coerce')
#mean, ignoring NaN values

column_mean = np.nanmean(hp_float)
#replacing NaN values
new_h_power =hp_float.copy()
new_h_power[np.isnan(new_h_power)] = column_mean
#inc by 10%
new_h_power_b = new_h_power * 1.10
new_h_power_b

array([143.        , 181.5       , 165.        , 165.        ,
       154.        , 217.8       , 242.        , 236.5       ,
       247.5       , 209.        , 187.        , 176.        ,
       165.        , 247.5       , 104.5       , 104.5       ,
       106.7       ,  93.5       ,  96.8       ,  50.6       ,
        95.7       ,  99.        , 104.5       , 124.3       ,
        99.        , 236.5       , 220.        , 231.        ,
       212.3       ,  96.8       ,  99.        , 104.5       ,
       114.91632653, 110.        , 115.5       , 110.        ,
        96.8       , 110.        , 181.5       , 192.5       ,
       168.3       , 165.        , 198.        , 187.        ,
       192.5       , 121.        ,  79.2       , 110.        ,
        96.8       ,  94.6       ,  99.        ,  77.        ,
        83.6       ,  71.5       ,  75.9       ,  66.        ,
        77.        , 104.5       ,  88.        ,  59.4       ,
        99.        ,  94.6       , 181.5       , 192.5 

6. BooleanIndexing

Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing.

In [48]:
europe_or = data_cars['origin']== 2
avg_disp = np.mean(data_cars['displacement'][europe_or])
avg_disp

np.float64(109.14285714285714)

7. MatrixOperations

Create a 2D NumPy array containing the columns mpg, horsepower, and weight. Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [47]:
mat_2d = df[['mpg', 'horsepower', 'weight']].to_numpy()
mat_2d

array([[  18.,  130., 3504.],
       [  15.,  165., 3693.],
       [  18.,  150., 3436.],
       ...,
       [  32.,   84., 2295.],
       [  28.,   79., 2625.],
       [  31.,   82., 2720.]])

In [49]:
array_2d = np.column_stack((
    mpg_array.astype(float),
    new_h_power.astype(float),
    wgt_array.astype(float)
))
array_2d

array([[  18.,  130., 3504.],
       [  15.,  165., 3693.],
       [  18.,  150., 3436.],
       ...,
       [  32.,   84., 2295.],
       [  28.,   79., 2625.],
       [  31.,   82., 2720.]])

In [50]:
array_2d.shape

(398, 3)

In [51]:
vector = np.array([1, 0.5, -0.2])

In [52]:
result =array_2d @ vector
result

array([-617.8       , -641.1       , -594.2       , -595.6       ,
       -602.8       , -754.2       , -746.8       , -740.9       ,
       -758.5       , -660.        , -612.6       , -627.8       ,
       -662.2       , -490.7       , -402.9       , -497.1       ,
       -488.3       , -453.9       , -355.        , -318.        ,
       -465.9       , -417.        , -402.5       , -364.3       ,
       -463.6       , -805.5       , -765.2       , -760.4       ,
       -840.9       , -355.        , -379.8       , -373.1       ,
       -331.96530612, -457.8       , -619.3       , -598.8       ,
       -597.4       , -589.6       , -745.3       , -791.3       ,
       -740.3       , -730.2       , -889.        , -851.2       ,
       -927.5       , -519.4       , -423.6       , -587.4       ,
       -565.8       , -378.        , -351.6       , -349.8       ,
       -345.        , -291.1       , -253.1       , -309.8       ,
       -330.        , -384.1       , -360.2       , -400.8    

In [ ]:
result.shape

(398,)

8. Sorting

Use NumPy to sort the cars by model_year in descending order and display the first five car names.

In [ ]:
column_index = df.columns.get_loc('model year')
column_index

6

In [7]:
#in ascending
sorted_asc = np.argsort(data_cars['model_year'])
sorted_desc = sorted_asc [::-1]
#sorted_desc
new_5 = data_cars['car_name'][sorted_desc[:5]].tolist()
new_5

['dodge aries se',
 'pontiac phoenix',
 'pontiac j2000 se hatchback',
 'chevrolet cavalier 2-door',
 'chevrolet cavalier wagon']

9. Correlation

Compute the Pearson correlation coefficient between mpg and weight using NumPy.


In [ ]:
mpg_array.dtype

dtype('float64')

In [ ]:
wgt_array.dtype

dtype('int64')

In [53]:
weight_arr = wgt_array.astype(float)
correltn_matrix = np.corrcoef(mpg_array, weight_arr)
correltn_matrix

array([[ 1.        , -0.83174093],
       [-0.83174093,  1.        ]])

In [ ]:
pearson_crr = correltn_matrix[0, 1]
pearson_crr

np.float64(-0.8317409332443352)

10. Conditional Aggregates

Calculate the mean mpg for cars grouped by the number of cylinders using NumPy techniques.

In [54]:
mpg_array
mean_mpg = {}

In [ ]:
cyl_data = data_cars['cylinders']
unique_cylinders = np.unique(cyl_data)

In [ ]:
for cyl_count in unique_cylinders:
   current = (cyl_data == cyl_count)
   avg_mpg = np.nanmean(mpg_array[current].astype(float))
   mean_mpg[cyl_count] = avg_mpg
for cyl, mean_val in mean_mpg.items():
    print(f"Cylinders: {cyl}, Mean MPG: {mean_val:.2f}")

Cylinders: 3, Mean MPG: 20.55
Cylinders: 4, Mean MPG: 29.29
Cylinders: 5, Mean MPG: 27.37
Cylinders: 6, Mean MPG: 19.99
Cylinders: 8, Mean MPG: 14.96


## Pandas Problems

1. BasicExploration

Load the dataset into a Pandas DataFrame. Display:

○ The first 10 rows

○ The total number of rows and columns

○ Summary statistics for numerical columns

In [ ]:
df = pd.read_csv('auto-mpg.csv')
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [ ]:
df.shape

(398, 9)

In [ ]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

2. FilteringandIndexing

Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.

In [8]:
filtered_df = df[(df['model year'] == 75) & (df['weight'] < 3000)]

In [9]:
result = filtered_df[['car name', 'weight', 'mpg']]
result

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

3. HandlingMissingData

Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [10]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64


In [11]:
df['horsepower'] = df['horsepower'].replace('?', np.nan)

In [12]:
df['horsepower'] = df['horsepower'].astype(float)

In [14]:
median_value = df['horsepower'].median()
df['horsepower'] = df['horsepower'].fillna(median_value)

In [15]:
print(df['horsepower'].isnull().sum())

0


4. DataTransformation

Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [17]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df['power_to_weight_ratio']

0      0.037100
1      0.044679
2      0.043655
3      0.043694
4      0.040591
         ...   
393    0.030824
394    0.024413
395    0.036601
396    0.030095
397    0.030147
Name: power_to_weight_ratio, Length: 398, dtype: float64

In [24]:
print(df.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name',
       'power_to_weight_ratio'],
      dtype='object')


5. GroupBy

Group the cars by origin and calculate the mean mpg for each group.

In [20]:
origin_mean = df.groupby('origin')['mpg'].mean()
print(origin_mean)

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


6. Sorting

Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [21]:
top_10_mpg = df.sort_values(by='mpg', ascending=False)
top_10_mpg.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

7.  Apply Function

Create a new column performance_score using a custom function:

 def performance_score(row):

return row['mpg'] * row['acceleration'] / row['weight']

Apply this function to each row and store the result in the new column.


In [25]:
#custom function
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

In [26]:
df['performance_score'] = df.apply(performance_score, axis=1)
df['performance_score']

0      0.061644
1      0.046710
2      0.057625
3      0.055928
4      0.051754
         ...   
393    0.150968
394    0.508169
395    0.161743
396    0.198400
397    0.221103
Name: performance_score, Length: 398, dtype: float64

8. VisualizationPreparation

Generate a summary DataFrame with:

○ Average mpg, weight, and horsepower for each model_year.

In [29]:
summary_df = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()
summary_df

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

9. ExportingData

Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [33]:
#cars with mpg>30
high_mpg = df[df['mpg'] > 30]
high_mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
53   31.0          4          71.0        65.0    1773          19.0   
54   35.0          4          72.0        69.0    1613          18.0   
129  31.0          4          79.0        67.0    1950          19.0   
131  32.0          4          71.0        65.0    1836          21.0   
144  31.0          4          76.0        52.0    1649          16.5   

     model year  origin             car name  power_to_weight_ratio  \
53           71       3  toyota corolla 1200               0.036661   
54           71       3          datsun 1200               0.042777   
129          74       3          datsun b210               0.034359   
131          74       3  toyota corolla 1200               0.035403   
144          74       3        toyota corona               0.031534   

     performance_score  
53            0.332205  
54            0.390577  
129           0.302051  
131           0.366013  
144           0.310188

In [32]:
high_mpg_subset = high_mpg[['mpg', 'cylinders', 'horsepower', 'weight']]
high_mpg_subset.head(2)

mpg  cylinders  horsepower  weight
53  31.0          4        65.0    1773
54  35.0          4        69.0    1613

In [34]:
# saving to csv
high_mpg_subset.to_csv('high_mpg_cars.csv', index=False)

In [35]:
high_mpg_cars = pd.read_csv('high_mpg_cars.csv')
high_mpg_cars.head(2)

mpg  cylinders  horsepower  weight
0  31.0          4        65.0    1773
1  35.0          4        69.0    1613

 10. Finding Anomalies

Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically:

● Calculate the IQR for mpg.

● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.

● Create a DataFrame of cars classified as outliers, displaying car_name, mpg, and model_year.

In [36]:
#IQR for mpg.
#(25th percentile)
Q1 = df['mpg'].quantile(0.25)
#50th
Q2 = df['mpg'].quantile(0.50)
# 75th percentile
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1
print(f"IQR for mpg: {IQR}")

IQR for mpg: 11.5


In [37]:
# outliers
lower_bound = Q1 - 1.5 * IQR
print(f"Lower Bound: {lower_bound}")
upper_bound = Q3 + 1.5 * IQR
print(f"Upper Bound: {upper_bound}")

Lower Bound: 0.25
Upper Bound: 46.25


In [38]:
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]
outliers

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   

     model year  origin   car name  power_to_weight_ratio  performance_score  
322          80       3  mazda glc               0.030806           0.395327

In [39]:
len(outliers)

1

In [40]:
outlier_cars = outliers[['car name','mpg', 'model year']]
outlier_cars

car name   mpg  model year
322  mazda glc  46.6          80